export enum ErrorsEnum {
  USER_NOT_ACCOUNT_CONTACT = 'User must be account contact',
  USER_NOT_VENDOR_CONTACT = 'User must be vendor contact',
  REFERENCE_NOT_SELECTED = 'This reference dont selected',
  EULA_ALREADY_APPROVED = 'EULA already approved.',
  USER_DONT_EXITS = 'User does not exist.',
  USER_ALREADY_EXIST = 'A user with this email already exists',
  MEETING_DONT_EXIST = 'Meeting does not exist',
  MEETING_FINISHED = 'Meeting finished',
  MEETING_CANCELLED = 'Meeting already cancelled',
  ACTIVE_MEETING_STATISTIC_DONT_EXIST = 'Active meeting call statistic does not exist',
  USER_NOT_IN_MEETING = 'User not in meeting',
  INVALID_PATH_UUID = 'pathParam must be uuid',
  INVALID_UUID = 'Invalid uuid',
  LINK_INVALID = 'Link invalid',
  FORBIDDEN = 'Forbidden',
  NOT_FOUND = 'Not found',
  UNAUTHORIZED = 'Unauthorized',
  INTERNAL_SERVER_ERROR = 'Internal Server Error',
  INVALID_NOTIFICATION_CONTEXT = 'Invalid notification context',
  ALL_ACCOUNTS_ARE_BUSY = 'All zoom accounts are busy.',
  NOT_STARTED = 'Not started',
  ACCEPTED_TIMESLOT_DOES_NOT_EXIST = 'Accepted timeslot does not exist',
  TIMESLOT_CONFLICT = 'Meeting already has scheduled time slot at this time',
  USER_ALREADY_ACCOUNT_CONTACT = 'User already reference or prospect',
  INVALID_USER_ZOOM_ID = 'UserZoomId must be valid number',
  INVALID_MAGIC_LINK = 'Invalid magic link',
  INVALID_JOIN_LINK = 'Invalid join link',
  USER_LOCKED = 'Your account is locked, please contact your administrator',
  NOT_IMPLEMENTED = 'This functionality dont implemented',
  INVALID_LIMIT_VALUE = 'Invalid limit value',
  INSUFFICIENT_FUNDS = 'Insufficient funds',
  EMAIL_IS_REQUIRED_AND_MUST_BE_VALID = 'Email is required and must be valid email',
  CANNOT_PARSE_AUTHENTICATED_USER_ID = 'Cannot parse authenticated user id',
  USER_NOT_VENDOR = 'User not vendor',
  ACCOUNT_ID_MUST_BE_UUID = 'Account id must be uuid',
  INVALID_STATUS_FOR_A_USER = 'The status is not valid for a user',
  MISSING_REQUIRED_FIELD = 'Missing required field',
  NO_OBJECT_FOUND = 'No object found',
  MISSING_REFRESH_TOKEN = 'Missing refresh token',
  INVALID_DROPDOWN_TYPE_OR_NO_CUSTOM_FIELD_VALUES = 'Invalid dropdown type or no custom field values',
  USER_MUST_BE_A_VENDOR_ADMIN = 'The logged in user must be a vendor admin',

  AVAILABILITY_CANNOT_BE_LESS_THAN_ZERO = 'Availability cannot be less than zero',
  AVAILABILITY_DOES_NOT_EXIST = 'Availability does not exist',
  CURRENT_AVAILABILITY_CANNOT_BE_BIGGER_THAN_MAX_AVAILABILITY = 'Current availability cannot be bigger than max availability',

  VENDOR_ALREADY_EXISTS = 'Vendor already exists',
  DEETO_USERS_ONLY = 'Only Deeto users are allowed to use this functionality',
  NO_NOTIFICATION_TEMPLATE = 'No notification template',
  MEDIA_NOT_SUPPORTED = 'Media not supported',

  MAPPING_SETTING_DOES_NOT_EXIST = 'Mapping settings does not exist',
}